version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
#    image: ametnes/horilla:1.2.1-20241212
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      HORILLA_ADMIN_PHONE: 12343
      HORILLA_ADMIN_EMAIL: admin@example.com
      HORILLA_ADMIN_USER: admin@example.com
      HORILLA_ADMIN_PASSWORD: password
      HORILLA_ADMIN_FIRST_NAME: Admin
      HORILLA_ADMIN_LAST_NAME: Admin
      HORILLA_NUM_WORKERS: "3"
      HORILLA_TIMEOUT: "120"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/horilla"
      HORILLA_EMAIL_HOST: 'smtp.gmail.com'
      HORILLA_EMAIL_PORT: "587"
      HORILLA_EMAIL_HOST_USER: "user"
      HORILLA_EMAIL_HOST_PASSWORD: 'BlPlvGo'
      HORILLA_EMAIL_USE_TLS: "true"
      LOG_LEVEL: DEBUG
    command: ./entrypoint.sh
    volumes:
      - ./horilla:/app/horilla
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: horilla
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - horilla-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  horilla-data:
